obj-y += rtl8367c.o \
acl.o \
chip.o \
cpu.o \
dot1x.o \
eee.o \
i2c.o \
igmp.o \
interrupt.o \
l2.o \
leaky.o \
led.o \
mirror.o \
oam.o \
port.o \
ptp.o \
qos.o \
rate.o \
rldp.o \
rtk_switch.o \
stat.o \
storm.o \
svlan.o \
trap.o \
trunk.o \
vlan.o 
obj-y += dal/
obj-y += dal/rtl8367c/
