# SPDX-License-Identifier: GPL-2.0
#CROSS_COMPILE=../../../../../../../prebuilts/gcc/linux-x86/aarch64/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-
#CC := $(CROSS_COMPILE)gcc
source /opt/fsl-imx-xwayland/6.12-walnascar/environment-setup-armv8a-poky-linux

PROGS := slcanfd

all: $(PROGS)

clean:
	rm -fr $(PROGS)
