obj-$(CONFIG_LIBERTAS)		+= libertas/

obj-$(CONFIG_LIBERTAS_THINFIRM)	+= libertas_tf/
obj-$(CONFIG_MWIFIEX)	+= mwifiex/
obj-$(CONFIG_MWIFIEX_PCIE_8897)	+= mrvl8897/
obj-$(CONFIG_MWIFIEX_USB_8897)	+= mrvl8897/

obj-$(CONFIG_MWL8K)	+= mwl8k.o
