# Defines vendor ID and product ID pairs for USB wireless devices
# Format: vid_pid_N=0xVVVV:0xPPPP where VVVV is vendor ID and PPPP is product ID
# note: could not use same VID and PID for different wireless devices, max support 3 wireless devices and 10 pairs of VID:PID
USBIW610={
    vid_pid_0=0x123:0x456
    vid_pid_1=0x789:0xabc
}
