#
# File:	mlancsi.conf
#
# Copyright 2025, NXP
#
#################################################################################

# CSI event configuration file
# Lines that start with # are treated as comments
# Each line should not exceed 80 characters
# Format: TYPE=value
#
#################################################################################
#################################################################################
CSI_EVENT_CFG={
# Source Address of packets to process CSI from to generate Ambient Motion Index
MAC_ADDR=02:50:43:24:C0:C1

# Packet type
# 0: legacy - 11a/g
# 1: HT 	- 11n
# 2: VHT	- 11ac
# 3: HE		- 11ax
PACKET_TYPE=0

# 0: 20MHz, 1:40MHz , 2:80MHz
FORMAT_BW=0

# Reference Update
# 0: "static" 		- frst , no updates
# 1: "IIR filter"	- first CSI is reference, update with IIR fitler coefficient alpha
# 2: "Kalman filter"- first CSI is reference, update with Kalaman fitler
UPDATE_REF=0

# IIR update filter H_ref_n = (1-alpha)*H_ref_{n-1) + alpha*H_n
# values within [0,1]
IIR_ALPHA=0.1

# Kalman filter parameters
# Kalman filter update step:
# H_ref_n = (1-K_n)*H_ref_{n-1) + K_n*H_n
# where
# kp_0 = KALMAN_P0 - initiatlization
# p_n = kp_{n-1} + KALMAN_ALPHA*delta_time
# S_n = p_n + KALMAN_N0
# K_n = p_n / S_n
# kp_n = (1 - K_n) * p_n
# delta_time in seconds
KALMAN_P0=0.5
KALMAN_ALPHA=0.005
KALMAN_N0=0.2

# Number of CSI
# 0: 	default, will run until app is killed
# 1-255:will run for this many CSI records
NUM_CSI=0
}

#################################################################################
