#twt_for_iw.conf: A duplicate of twt.conf without comments, specifically for twt configuration using iw.

twt_setup={
   Implicit=1
   Announced=0
   TriggerEnabled=0
   TWTInformationDisabled=0
   NegotiationType=0
   TWTWakeupDuration=64
   FlowIdentifier=0
   HardConstraint=1
   TWTExponent=10
   TWTMantissa=512
   TWTRequestType=0
   BeaconMissThreshold=60
}

twt_teardown={
    FlowIdentifier=0
    NegotiationType=0
    TearDownAllTWT=0
}

twt_information={
    FlowIdentifier=0
    SuspendDuration=3000
}

btwt_AP_config_get={
        ap_bcast_bet_sta_wait=0
        Ap_Bcast_Offset=0
        bcastTWTLI=0
        count=5
}

btwt_AP_config_set={
        ap_bcast_bet_sta_wait=0
        Ap_Bcast_Offset=0
        bcastTWTLI=0
        count=2

        btwtId0=0
        Ap_Bcast_Mantissa0=112
        Ap_Bcast_Exponent0=10
        nominalwake0=128

        btwtId1=1
        Ap_Bcast_Mantissa1=32
        Ap_Bcast_Exponent1=10
        nominalwake1=64

        btwtId2=2
        Ap_Bcast_Mantissa2=32
        Ap_Bcast_Exponent2=10
        nominalwake2=64

        btwtId3=3
        Ap_Bcast_Mantissa3=32
        Ap_Bcast_Exponent3=10
        nominalwake3=64

        btwtId4=4
        Ap_Bcast_Mantissa4=32
        Ap_Bcast_Exponent4=10
        nominalwake4=64
}
